// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/**
 * No-op lock for iOS Capacitor WebView compatibility.
 * 
 * The default navigator.locks API deadlocks on iOS when the app
 * is suspended and resumed. Since mobile apps are single-instance,
 * we don't need cross-tab locking.
 * 
 * See: https://github.com/supabase/auth-js/issues/866
 */
const noOpLock = async <T>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<T>
): Promise<T> => {
  return await fn();
};

const clientOptions = {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: noOpLock,
  }
};

// Mutable client instance - can be recreated on cold start recovery
let supabaseInstance: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  clientOptions
);

/**
 * Recreate the Supabase client with a fresh instance.
 * Call this on cold start after failed boot detection to clear
 * any corrupted internal state from iOS hard-close.
 * 
 * The Supabase client can get into a broken state when iOS force-kills
 * the app mid-operation, leaving stale network connections and locked
 * auth state. A fresh instance resolves this.
 */
export const recreateSupabaseClient = (): SupabaseClient<Database> => {
  console.log('[SupabaseClient] Recreating client instance for fresh start');
  supabaseInstance = createClient<Database>(
    SUPABASE_URL, 
    SUPABASE_PUBLISHABLE_KEY, 
    clientOptions
  );
  return supabaseInstance;
};

/**
 * Proxy that forwards all property access to the current instance.
 * This allows the underlying client to be swapped without breaking imports.
 * 
 * All existing code using `import { supabase } from '...'` will automatically
 * use the new instance after recreateSupabaseClient() is called.
 */
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get: (_, prop: keyof SupabaseClient<Database>) => {
    return supabaseInstance[prop];
  },
});
